# Generated by Django 5.0.4 on 2024-05-12 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hprouting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hprouting.building'),
        ),
    ]
