# Generated by Django 5.0.4 on 2024-05-12 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hprouting', '0002_site_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteadjacency',
            name='from_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_site', to='hprouting.site'),
        ),
        migrations.AddField(
            model_name='siteadjacency',
            name='to_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_site', to='hprouting.site'),
        ),
    ]
