# Generated by Django 5.0.4 on 2024-05-12 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hprouting', '0003_siteadjacency_from_site_siteadjacency_to_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteadjacency',
            name='from_site',
        ),
        migrations.RemoveField(
            model_name='siteadjacency',
            name='to_site',
        ),
        migrations.AddField(
            model_name='siteadjacency',
            name='a_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_site', to='hprouting.site'),
        ),
        migrations.AddField(
            model_name='siteadjacency',
            name='b_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_site', to='hprouting.site'),
        ),
    ]
