# Generated by Django 5.0.4 on 2024-05-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hprouting', '0004_remove_siteadjacency_from_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='img',
            field=models.ImageField(upload_to='media/sites'),
        ),
    ]
