# Generated by Django 5.0.4 on 2024-04-15 01:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ventura", "0002_colleges_users_delete_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="college_id",
        ),
        migrations.DeleteModel(
            name="Colleges",
        ),
    ]
